/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoletaRouteImport } from './routes/roleta'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicTrackEventRouteImport } from './routes/api/public/track-event'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiPublicLogVisitRouteImport } from './routes/api/public/log-visit'
import { Route as ApiPublicGeoRouteImport } from './routes/api/public/geo'

const RoletaRoute = RoletaRouteImport.update({
  id: '/roleta',
  path: '/roleta',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicTrackEventRoute = ApiPublicTrackEventRouteImport.update({
  id: '/api/public/track-event',
  path: '/api/public/track-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLogVisitRoute = ApiPublicLogVisitRouteImport.update({
  id: '/api/public/log-visit',
  path: '/api/public/log-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGeoRoute = ApiPublicGeoRouteImport.update({
  id: '/api/public/geo',
  path: '/api/public/geo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/loja': typeof LojaRoute
  '/pagamento': typeof PagamentoRoute
  '/quiz': typeof QuizRoute
  '/roleta': typeof RoletaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/public/log-visit': typeof ApiPublicLogVisitRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/track-event': typeof ApiPublicTrackEventRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/loja': typeof LojaRoute
  '/pagamento': typeof PagamentoRoute
  '/quiz': typeof QuizRoute
  '/roleta': typeof RoletaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/public/log-visit': typeof ApiPublicLogVisitRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/track-event': typeof ApiPublicTrackEventRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/loja': typeof LojaRoute
  '/pagamento': typeof PagamentoRoute
  '/quiz': typeof QuizRoute
  '/roleta': typeof RoletaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/public/log-visit': typeof ApiPublicLogVisitRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/track-event': typeof ApiPublicTrackEventRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/loja'
    | '/pagamento'
    | '/quiz'
    | '/roleta'
    | '/admin'
    | '/produto/$slug'
    | '/api/public/geo'
    | '/api/public/log-visit'
    | '/api/public/track'
    | '/api/public/track-event'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/loja'
    | '/pagamento'
    | '/quiz'
    | '/roleta'
    | '/admin'
    | '/produto/$slug'
    | '/api/public/geo'
    | '/api/public/log-visit'
    | '/api/public/track'
    | '/api/public/track-event'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/checkout'
    | '/loja'
    | '/pagamento'
    | '/quiz'
    | '/roleta'
    | '/_authenticated/admin'
    | '/produto/$slug'
    | '/api/public/geo'
    | '/api/public/log-visit'
    | '/api/public/track'
    | '/api/public/track-event'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  LojaRoute: typeof LojaRoute
  PagamentoRoute: typeof PagamentoRoute
  QuizRoute: typeof QuizRoute
  RoletaRoute: typeof RoletaRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiPublicGeoRoute: typeof ApiPublicGeoRoute
  ApiPublicLogVisitRoute: typeof ApiPublicLogVisitRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  ApiPublicTrackEventRoute: typeof ApiPublicTrackEventRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roleta': {
      id: '/roleta'
      path: '/roleta'
      fullPath: '/roleta'
      preLoaderRoute: typeof RoletaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/track-event': {
      id: '/api/public/track-event'
      path: '/api/public/track-event'
      fullPath: '/api/public/track-event'
      preLoaderRoute: typeof ApiPublicTrackEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/log-visit': {
      id: '/api/public/log-visit'
      path: '/api/public/log-visit'
      fullPath: '/api/public/log-visit'
      preLoaderRoute: typeof ApiPublicLogVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/geo': {
      id: '/api/public/geo'
      path: '/api/public/geo'
      fullPath: '/api/public/geo'
      preLoaderRoute: typeof ApiPublicGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  LojaRoute: LojaRoute,
  PagamentoRoute: PagamentoRoute,
  QuizRoute: QuizRoute,
  RoletaRoute: RoletaRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiPublicGeoRoute: ApiPublicGeoRoute,
  ApiPublicLogVisitRoute: ApiPublicLogVisitRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  ApiPublicTrackEventRoute: ApiPublicTrackEventRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
